# Generated by Django 2.2 on 2020-06-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.validators
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/worker/%Y/%m/%d', validators=[manager.validators.validate_file_size], verbose_name='avatar')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('departament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Departament')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Managers')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_finish', models.BooleanField(default=False)),
                ('asign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Managers')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
    ]
