# Generated by Django 2.2 on 2020-06-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Departament'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Managers'),
        ),
    ]
