# Generated by Django 2.2 on 2020-06-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20200609_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
    ]
