# Generated by Django 2.2 on 2020-06-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
