# Generated by Django 2.2 on 2020-06-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.validators
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/manager/%Y/%m/%d', validators=[manager.validators.validate_file_size], verbose_name='avatar')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('responsible', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.Managers')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
